name: Security check - Bandit

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Job to perform Bandit scan on the codebase.
  sast_scan:
    name: Run Bandit Scan
    runs-on: ubuntu-latest

    steps:
      # Check out the code from the repository.
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Python for the Bandit scan.
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: 3.9

      # Install Bandit tool for static analysis of Python code.
      - name: Install Bandit
        run: pip install bandit

      # Run Bandit scan on the codebase and generate a JSON report.
      - name: Run Bandit Scan
        run: bandit -ll -ii -r . -f json -o bandit-report.json

      # Upload the Bandit scan report as an artifact for later analysis.
      - name: Upload Bandit Scan Artifact
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: bandit-findings
          path: bandit-report.json
